version: '3.1'

volumes:
  mongo:

services:
  mongo:
    image: mongo

    ports:
      - 27017:27017

    volumes:
      - mongo:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=jabari
      - MONGO_INITDB_ROOT_PASSWORD=password
