version: '3.1'

volumes:
  postgres:

secrets:
  DEFAULT_PASSWORD:
    external:
      name: "DEFAULT_PASSWORD"

services:
  postgres:
    image: postgres

    ports:
      - 5432:5432

    volumes:
      - postgres:/var/lib/postgresql/data

    secrets:
    - source: "DEFAULT_PASSWORD"
      target: "DEFAULT_PASSWORD"
      uid: "0"
      gid: "0"
      mode: 0444

    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DEFAULT_PASSWORD
