version: '2'

volumes:
  nextcloud:
  postgres:

services:
  db:
    image: postgres

    ports:
      - 5432:5432

    volumes:
      - postgres:/var/lib/postgresql/data

    restart: always

    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=pi
      - POSTGRES_PASSWORD=raspberry

  app:
    image: nextcloud
    
    ports:
      - 80:80

    depends_on:
      - db

    volumes:
      - nextcloud:/var/www/html

    restart: always

    environment:
      - NEXTCLOUD_ADMIN_USER=pi
      - NEXTCLOUD_ADMIN_PASSWORD=raspberry
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=pi
      - POSTGRES_PASSWORD=raspberry
