version: '3'

volumes:
  portainer:

services:
  portainer:
    image: portainer/portainer

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data portainer/portainer

    ports:
      - 9000:9000

    deploy:
      mode: replicated
      replicas: 1
