version: '3.1'

services:

  server:
    image: jabaridash/cluster_test_server
    build: server

    ports:
      - 8085:8085

    deploy:
      restart_policy:
        condition: on-failure

#-------------------------------------------------------------------------------

  client:
    image: jabaridash/cluster_test_client
    build: client

    ports:
     - 5000:5000

    depends_on:
      - "server"

    deploy:
      restart_policy:
        condition: on-failure

#-------------------------------------------------------------------------------

networks:
  default:
    external:
      name: cluster_test_app
