version: '3.1'

services:
  redis:
    image: "redis:alpine"

  # client:
  #   image: jabaridash/cluster_test_client
  #
  #   ports:
  #    - 5000:5000
  #
  #   networks:
  #     - cluster_test_app
  #
  #   deploy:
  #     restart_policy:
  #       condition: on-failure

#-------------------------------------------------------------------------------

  server:
    image: jabaridash/cluster_test_server

    ports:
      - 8085:8085

    networks:
      - cluster_test_app

    deploy:
      restart_policy:
        condition: on-failure

#-------------------------------------------------------------------------------

networks:
  cluster_test_app:
